name: pr-labeling

on: pull_request

jobs:
    build:
        runs-on: ubuntu-latest
        name: labeling
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
            
            - name: Update daily data
              run: npm run label